# Setting up

In [19]:
# IMPORTS
import pandas as pd
import time

In [20]:
# PARAMETERS

train_path = "data/basic_dataset.csv"
# for testing: train_path = "data/small_dataset.csv"
stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats.csv"
save_output = True

In [21]:
# LOAD DATA

start_time = time.time()
chunk = pd.read_csv(train_path, chunksize=1000000)
print(f"load chunk: {time.time() - start_time:.2f}s")

start_time = time.time()
df = pd.concat(chunk)
print(f"concat df: {time.time() - start_time:.2f}s")

load chunk: 0.02s
concat df: 22.49s

# Describing the dataset

### Describing the entire dataset

In [22]:
# save to csv the stats
stats = []

for column in df.columns:
    stats.append(df[column].describe())

df_stats = pd.concat(stats, axis=1).T

if save_output: df_stats.to_csv(stats_path)

In [23]:
df_stats.head()

,count,mean,std,min,25%,50%,75%,max
srch_id,4958347.0,166366.561096,96112.230102,1.00,82936.00,166507.00,249724.00,332785.0
site_id,4958347.0,9.953133,7.646890,1.00,5.00,5.00,14.00,34.0
visitor_location_country_id,4958347.0,175.340453,65.916249,1.00,100.00,219.00,219.00,231.0
visitor_hist_starrating,251866.0,3.374334,0.692519,1.41,2.92,3.45,3.93,5.0
visitor_hist_adr_usd,252988.0,176.022659,107.254493,0.00,109.81,152.24,213.49,1958.7

In [24]:
for row_name in df_stats.index:
     df_stats.loc[row_name, "count_missing"] = df[row_name].isna().sum()
     
if save_output: df_stats.to_csv(stats_path)

In [28]:
# describe the dataframe with describe method with 2 decimals
df.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
srch_id,4958347.0,166366.56,96112.23,1.00,82936.00,166507.00,249724.00,332785.00
site_id,4958347.0,9.95,7.65,1.00,5.00,5.00,14.00,34.00
visitor_location_country_id,4958347.0,175.34,65.92,1.00,100.00,219.00,219.00,231.00
visitor_hist_starrating,251866.0,3.37,0.69,1.41,2.92,3.45,3.93,5.00
visitor_hist_adr_usd,252988.0,176.02,107.25,0.00,109.81,152.24,213.49,1958.70
prop_country_id,4958347.0,173.97,68.35,1.00,100.00,219.00,219.00,230.00
prop_id,4958347.0,70079.18,40609.92,1.00,35010.00,69638.00,105168.00,140821.00
prop_starrating,4958347.0,3.18,1.05,0.00,3.00,3.00,4.00,5.00
prop_review_score,4950983.0,3.78,1.05,0.00,3.50,4.00,4.50,5.00
prop_brand_bool,4958347.0,0.63,0.48,0.00,0.00,1.00,1.00,1.00
prop_location_score1,4958347.0,2.87,1.53,0.00,1.79,2.77,4.04,6.98
prop_location_score2,3867999.0,0.13,0.16,0.00,0.02,0.07,0.18,1.00
prop_log_historical_price,4958347.0,4.32,1.83,0.00,4.45,4.91,5.31,6.21
position,4958347.0,16.86,10.43,1.00,8.00,16.00,26.00,40.00
price_usd,4958347.0,254.21,16001.24,0.00,85.00,122.00,184.96,19726328.00
promotion_flag,4958347.0,0.22,0.41,0.00,0.00,0.00,0.00,1.00
srch_destination_id,4958347.0,14042.63,8111.84,2.00,7101.00,13541.00,21084.00,28416.00
srch_length_of_stay,4958347.0,2.39,2.05,1.00,1.00,2.00,3.00,57.00
srch_booking_window,4958347.0,37.47,51.99,0.00,4.00,17.00,48.00,492.00
srch_adults_count,4958347.0,1.97,0.86,1.00,2.00,2.00,2.00,9.00
srch_children_count,4958347.0,0.35,0.73,0.00,0.00,0.00,0.00,9.00
srch_room_count,4958347.0,1.11,0.42,1.00,1.00,1.00,1.00,8.00
srch_saturday_night_bool,4958347.0,0.50,0.50,0.00,0.00,1.00,1.00,1.00
random_bool,4958347.0,0.30,0.46,0.00,0.00,0.00,1.00,1.00
click_bool,4958347.0,0.04,0.21,0.00,0.00,0.00,0.00,1.00
gross_bookings_usd,138390.0,386.28,821.19,0.00,124.00,218.40,429.79,159292.38
booking_bool,4958347.0,0.03,0.16,0.00,0.00,0.00,0.00,1.00

### Describing only the booked rowss

In [26]:
temp_df = df[df.booking_bool == 1]
stats = []
for column in temp_df.columns:
    stats.append(temp_df[column].describe())
df_stats = pd.concat(stats, axis=1).T

stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats_booked_rows.csv"
if save_output: df_stats.to_csv(stats_path)

In [27]:
for row_name in df_stats.index:
     df_stats.loc[row_name, "count_missing"] = temp_df[row_name].isna().sum()

if save_output: df_stats.to_csv(stats_path)