# Setting up

In [3]:
# IMPORTS
import pandas as pd
import time

In [1]:
# PARAMETERS

train_path = "data/training_set_VU_DM.csv"
# for testing: train_path = "data/small_dataset.csv"
stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats.csv"
save_output = True

In [4]:
# LOAD DATA

start_time = time.time()
chunk = pd.read_csv(train_path, chunksize=1000000)
print(f"load chunk: {time.time() - start_time:.2f}s")

start_time = time.time()
df = pd.concat(chunk)
print(f"concat df: {time.time() - start_time:.2f}s")

load chunk: 0.00s
concat df: 12.37s

# Describing the dataset

### Describing the entire dataset

In [16]:
# save to csv the stats
stats = []

for column in df.columns:
    stats.append(df[column].describe())

df_stats = pd.concat(stats, axis=1).T

if save_output: df_stats.to_csv(stats_path)

In [17]:
df_stats.head()

,count,mean,std,min,25%,50%,75%,max,unique,top,freq
srch_id,4958347.0,166366.561096,96112.230102,1.0,82936.0,166507.0,249724.0,332785.0,NaN,NaN,NaN
date_time,4958347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198615,2012-11-02 14:04:51,95
site_id,4958347.0,9.953133,7.64689,1.0,5.0,5.0,14.0,34.0,NaN,NaN,NaN
visitor_location_country_id,4958347.0,175.340453,65.916249,1.0,100.0,219.0,219.0,231.0,NaN,NaN,NaN
visitor_hist_starrating,251866.0,3.374334,0.692519,1.41,2.92,3.45,3.93,5.0,NaN,NaN,NaN

In [7]:
for row_name in df_stats.index:
     df_stats.loc[row_name, "count_missing"] = df[row_name].isna().sum()
     
if save_output: df_stats.to_csv(stats_path)

In [14]:
# describe the dataframe with describe method with 2 decimals
df.describe().round(2)

,srch_id,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
count,4958347.00,4958347.00,4958347.00,251866.00,252988.00,4958347.00,4958347.00,4958347.00,4950983.00,4958347.00,...,96174.00,315348.00,356422.00,138515.00,1916654.00,1987503.00,614730.00,4958347.00,138390.00,4958347.00
mean,166366.56,9.95,175.34,3.37,176.02,173.97,70079.18,3.18,3.78,0.63,...,17.25,0.15,0.08,19.43,-0.06,0.01,22.43,0.04,386.28,0.03
std,96112.23,7.65,65.92,0.69,107.25,68.35,40609.92,1.05,1.05,0.48,...,31.16,0.58,0.32,54.37,0.47,0.20,895.97,0.21,821.19,0.16
min,1.00,1.00,1.00,1.41,0.00,1.00,1.00,0.00,0.00,0.00,...,2.00,-1.00,-1.00,2.00,-1.00,-1.00,2.00,0.00,0.00,0.00
25%,82936.00,5.00,100.00,2.92,109.81,100.00,35010.00,3.00,3.50,0.00,...,6.00,0.00,0.00,7.00,0.00,0.00,7.00,0.00,124.00,0.00
50%,166507.00,5.00,219.00,3.45,152.24,219.00,69638.00,3.00,4.00,1.00,...,11.00,0.00,0.00,12.00,0.00,0.00,11.00,0.00,218.40,0.00
75%,249724.00,14.00,219.00,3.93,213.49,219.00,105168.00,4.00,4.50,1.00,...,18.00,1.00,0.00,20.00,0.00,0.00,17.00,0.00,429.79,0.00
max,332785.00,34.00,231.00,5.00,1958.70,230.00,140821.00,5.00,5.00,1.00,...,1620.00,1.00,1.00,9900.00,1.00,1.00,149400.00,1.00,159292.38,1.00

### Describing only the booked rowss

In [12]:
temp_df = df[df.booking_bool == 1]
stats = []
for column in temp_df.columns:
    stats.append(temp_df[column].describe())
df_stats = pd.concat(stats, axis=1)

stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats_booked_rows.csv"
if save_output: df_stats.to_csv(stats_path)

In [ ]:
for row_name in df_stats.index:
     df_stats.loc[row_name, "count_missing"] = temp_df[row_name].isna().sum()
     
if save_output: df_stats.to_csv(stats_path)