# Setting up

In [6]:
# IMPORTS
import pandas as pd
import time
import matplotlib.pyplot as plt

In [3]:
# PARAMETERS

train_path = "data/basic_dataset.csv"
train_path = "data/training_set_VU_DM.csv"
# for testing: train_path = "data/small_dataset.csv"
save_output = True

In [4]:
# LOAD DATA

start_time = time.time()
chunk = pd.read_csv(train_path, chunksize=1000000)
print(f"load chunk: {time.time() - start_time:.2f}s")

start_time = time.time()
df = pd.concat(chunk)
print(f"concat df: {time.time() - start_time:.2f}s")

load chunk: 0.00s
concat df: 10.69s

In [19]:
df.head()

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,893,3,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,10404,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
2,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,21315,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
3,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,27348,2,4.0,...,NaN,NaN,NaN,NaN,-1.0,0.0,5.0,0,NaN,0
4,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,29604,4,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0

# Describing the dataset

### Describing the entire dataset

In [31]:

df_stats = df.describe().round(2).T

In [30]:
df_stats

,count,mean,std,min,25%,50%,75%,max,count_missing
srch_id,4958347.0,166366.56,96112.23,1.00,82936.00,166507.00,249724.00,332785.00,0.0
site_id,4958347.0,9.95,7.65,1.00,5.00,5.00,14.00,34.00,0.0
visitor_location_country_id,4958347.0,175.34,65.92,1.00,100.00,219.00,219.00,231.00,0.0
visitor_hist_starrating,251866.0,3.37,0.69,1.41,2.92,3.45,3.93,5.00,129302.0
visitor_hist_adr_usd,252988.0,176.02,107.25,0.00,109.81,152.24,213.49,1958.70,129256.0
prop_country_id,4958347.0,173.97,68.35,1.00,100.00,219.00,219.00,230.00,0.0
prop_id,4958347.0,70079.18,40609.92,1.00,35010.00,69638.00,105168.00,140821.00,0.0
prop_starrating,4958347.0,3.18,1.05,0.00,3.00,3.00,4.00,5.00,0.0
prop_review_score,4950983.0,3.78,1.05,0.00,3.50,4.00,4.50,5.00,116.0
prop_brand_bool,4958347.0,0.63,0.48,0.00,0.00,1.00,1.00,1.00,0.0
prop_location_score1,4958347.0,2.87,1.53,0.00,1.79,2.77,4.04,6.98,0.0
prop_location_score2,3867999.0,0.13,0.16,0.00,0.02,0.07,0.18,1.00,14474.0
prop_log_historical_price,4958347.0,4.32,1.83,0.00,4.45,4.91,5.31,6.21,0.0
position,4958347.0,16.86,10.43,1.00,8.00,16.00,26.00,40.00,0.0
price_usd,4958347.0,254.21,16001.24,0.00,85.00,122.00,184.96,19726328.00,0.0
promotion_flag,4958347.0,0.22,0.41,0.00,0.00,0.00,0.00,1.00,0.0
srch_destination_id,4958347.0,14042.63,8111.84,2.00,7101.00,13541.00,21084.00,28416.00,0.0
srch_length_of_stay,4958347.0,2.39,2.05,1.00,1.00,2.00,3.00,57.00,0.0
srch_booking_window,4958347.0,37.47,51.99,0.00,4.00,17.00,48.00,492.00,0.0
srch_adults_count,4958347.0,1.97,0.86,1.00,2.00,2.00,2.00,9.00,0.0
srch_children_count,4958347.0,0.35,0.73,0.00,0.00,0.00,0.00,9.00,0.0
srch_room_count,4958347.0,1.11,0.42,1.00,1.00,1.00,1.00,8.00,0.0
srch_saturday_night_bool,4958347.0,0.50,0.50,0.00,0.00,1.00,1.00,1.00,0.0
srch_query_affinity_score,317406.0,-24.15,15.74,-326.57,-30.77,-20.45,-13.35,-2.49,127505.0
orig_destination_distance,3350565.0,1301.23,2023.95,0.01,139.80,386.60,1500.67,11666.64,44689.0
random_bool,4958347.0,0.30,0.46,0.00,0.00,0.00,1.00,1.00,0.0
comp1_rate,119930.0,0.48,0.64,-1.00,0.00,1.00,1.00,1.00,135222.0
comp1_inv,129559.0,0.03,0.23,-1.00,0.00,0.00,0.00,1.00,135039.0
comp1_rate_percent_diff,94439.0,244.23,1165.45,2.00,7.00,10.00,16.00,30389.00,135883.0
comp2_rate,2024672.0,0.04,0.45,-1.00,0.00,0.00,0.00,1.00,79896.0
comp2_inv,2130269.0,0.04,0.23,-1.00,0.00,0.00,0.00,1.00,76616.0
comp2_rate_percent_diff,556238.0,18.49,240.11,2.00,7.00,11.00,20.00,168893.00,120431.0
comp3_rate,1534288.0,0.02,0.46,-1.00,0.00,0.00,0.00,1.00,93092.0
comp3_inv,1650990.0,0.06,0.29,-1.00,0.00,0.00,0.00,1.00,89841.0
comp3_rate_percent_diff,472797.0,27.07,1012.92,2.00,7.00,11.00,18.00,199266.00,122832.0
comp4_rate,307378.0,-0.02,0.58,-1.00,0.00,0.00,0.00,1.00,129605.0
comp4_inv,343663.0,0.10,0.34,-1.00,0.00,0.00,0.00,1.00,128594.0
comp4_rate_percent_diff,131086.0,175.32,5757.74,2.00,7.00,11.00,19.00,1001584.00,134606.0
comp5_rate,2222373.0,0.02,0.52,-1.00,0.00,0.00,0.00,1.00,74653.0
comp5_inv,2360020.0,0.05,0.27,-1.00,0.00,0.00,0.00,1.00,70711.0
comp5_rate_percent_diff,841099.0,29.85,1340.26,2.00,7.00,12.00,21.00,607561.00,112667.0
comp6_rate,240157.0,0.13,0.56,-1.00,0.00,0.00,0.00,1.00,130693.0
comp6_inv,260976.0,0.08,0.30,-1.00,0.00,0.00,0.00,1.00,130070.0
comp6_rate_percent_diff,96174.0,17.25,31.16,2.00,6.00,11.00,18.00,1620.00,135352.0
comp7_rate,315348.0,0.15,0.58,-1.00,0.00,0.00,1.00,1.00,128249.0
comp7_inv,356422.0,0.08,0.32,-1.00,0.00,0.00,0.00,1.00,127147.0
comp7_rate_percent_diff,138515.0,19.43,54.37,2.00,7.00,12.00,20.00,9900.00,133843.0
comp8_rate,1916654.0,-0.06,0.47,-1.00,0.00,0.00,0.00,1.00,82796.0
comp8_inv,1987503.0,0.01,0.20,-1.00,0.00,0.00,0.00,1.00,80408.0
comp8_rate_percent_diff,614730.0,22.43,895.97,2.00,7.00,11.00,17.00,149400.00,119263.0
click_bool,4958347.0,0.04,0.21,0.00,0.00,0.00,0.00,1.00,0.0
gross_bookings_usd,138390.0,386.28,821.19,0.00,124.00,218.40,429.79,159292.38,0.0
booking_bool,4958347.0,0.03,0.16,0.00,0.00,0.00,0.00,1.00,0.0

In [35]:
for row_name in df_stats.index:
     df_stats.loc[row_name, "count_missing"] = df[row_name].isna().sum()

stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats.csv"


if save_output: df_stats.to_csv(stats_path)

### Describing only the booked rowss

In [10]:
booked_df = df[df.booking_bool == 1]

booked_stats = booked_df.describe().round(2).T

In [12]:
for row_name in df_stats.index:
     booked_stats.loc[row_name, "count_missing"] = booked_df[row_name].isna().sum()
     
stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats_booked_rows.csv"

if save_output: df_stats.to_csv(stats_path, index=False)

In [20]:
booked_stats

,count,mean,std,min,25%,50%,75%,max,count_missing
srch_id,138390.0,166642.78,96140.00,1.00,83312.75,166711.00,250249.75,332785.00,0.0
site_id,138390.0,9.89,7.64,1.00,5.00,5.00,14.00,34.00,0.0
visitor_location_country_id,138390.0,176.32,65.45,1.00,100.00,219.00,219.00,231.00,0.0
visitor_hist_starrating,9088.0,3.37,0.70,1.41,2.90,3.43,3.93,5.00,129302.0
visitor_hist_adr_usd,9134.0,176.36,110.90,0.00,109.69,151.30,212.20,1958.70,129256.0
prop_country_id,138390.0,174.47,67.88,1.00,100.00,219.00,219.00,230.00,0.0
prop_id,138390.0,69957.39,40718.90,2.00,34642.00,69261.00,104803.00,140821.00,0.0
prop_starrating,138390.0,3.31,0.95,0.00,3.00,3.00,4.00,5.00,0.0
prop_review_score,138274.0,3.94,0.80,0.00,3.50,4.00,4.50,5.00,116.0
prop_brand_bool,138390.0,0.66,0.47,0.00,0.00,1.00,1.00,1.00,0.0
prop_location_score1,138390.0,2.84,1.48,0.00,1.79,2.71,3.95,6.97,0.0
prop_location_score2,123916.0,0.19,0.19,0.00,0.05,0.13,0.26,1.00,14474.0
prop_log_historical_price,138390.0,4.31,1.83,0.00,4.48,4.93,5.29,6.21,0.0
position,138390.0,7.76,8.07,1.00,2.00,4.00,10.00,40.00,0.0
price_usd,138390.0,260.51,16258.30,0.00,82.00,112.83,159.00,3779565.00,0.0
promotion_flag,138390.0,0.30,0.46,0.00,0.00,0.00,1.00,1.00,0.0
srch_destination_id,138390.0,14080.95,8139.84,2.00,7097.00,13743.50,21173.00,28416.00,0.0
srch_length_of_stay,138390.0,2.09,1.69,1.00,1.00,2.00,3.00,30.00,0.0
srch_booking_window,138390.0,31.47,46.75,0.00,3.00,13.00,39.00,482.00,0.0
srch_adults_count,138390.0,1.95,0.88,1.00,1.00,2.00,2.00,9.00,0.0
srch_children_count,138390.0,0.37,0.74,0.00,0.00,0.00,0.00,9.00,0.0
srch_room_count,138390.0,1.13,0.44,1.00,1.00,1.00,1.00,8.00,0.0
srch_saturday_night_bool,138390.0,0.52,0.50,0.00,0.00,1.00,1.00,1.00,0.0
srch_query_affinity_score,10885.0,-22.01,15.15,-323.98,-27.57,-17.87,-12.27,-3.21,127505.0
orig_destination_distance,93701.0,1257.24,1989.27,0.01,135.01,358.25,1407.00,11635.43,44689.0
random_bool,138390.0,0.06,0.23,0.00,0.00,0.00,0.00,1.00,0.0
comp1_rate,3168.0,0.52,0.62,-1.00,0.00,1.00,1.00,1.00,135222.0
comp1_inv,3351.0,0.02,0.23,-1.00,0.00,0.00,0.00,1.00,135039.0
comp1_rate_percent_diff,2507.0,260.49,1227.89,2.00,7.00,10.00,16.00,14536.00,135883.0
comp2_rate,58494.0,0.09,0.47,-1.00,0.00,0.00,0.00,1.00,79896.0
comp2_inv,61774.0,0.04,0.24,-1.00,0.00,0.00,0.00,1.00,76616.0
comp2_rate_percent_diff,17959.0,20.06,32.90,2.00,7.00,12.00,24.00,1266.00,120431.0
comp3_rate,45298.0,0.06,0.48,-1.00,0.00,0.00,0.00,1.00,93092.0
comp3_inv,48549.0,0.05,0.29,-1.00,0.00,0.00,0.00,1.00,89841.0
comp3_rate_percent_diff,15558.0,18.92,35.08,2.00,7.00,12.00,21.00,2528.00,122832.0
comp4_rate,8785.0,0.04,0.57,-1.00,0.00,0.00,0.00,1.00,129605.0
comp4_inv,9796.0,0.09,0.33,-1.00,0.00,0.00,0.00,1.00,128594.0
comp4_rate_percent_diff,3784.0,168.83,4720.02,2.00,7.00,11.00,19.00,159260.00,134606.0
comp5_rate,63737.0,0.09,0.53,-1.00,0.00,0.00,0.00,1.00,74653.0
comp5_inv,67679.0,0.05,0.27,-1.00,0.00,0.00,0.00,1.00,70711.0
comp5_rate_percent_diff,25723.0,19.67,25.67,2.00,8.00,13.00,23.00,1510.00,112667.0
comp6_rate,7697.0,0.16,0.54,-1.00,0.00,0.00,0.00,1.00,130693.0
comp6_inv,8320.0,0.07,0.30,-1.00,0.00,0.00,0.00,1.00,130070.0
comp6_rate_percent_diff,3038.0,18.13,24.88,2.00,6.00,11.00,20.00,579.00,135352.0
comp7_rate,10141.0,0.18,0.56,-1.00,0.00,0.00,1.00,1.00,128249.0
comp7_inv,11243.0,0.07,0.31,-1.00,0.00,0.00,0.00,1.00,127147.0
comp7_rate_percent_diff,4547.0,21.09,44.90,2.00,8.00,12.00,22.00,1183.00,133843.0
comp8_rate,55594.0,0.00,0.48,-1.00,0.00,0.00,0.00,1.00,82796.0
comp8_inv,57982.0,0.01,0.22,-1.00,0.00,0.00,0.00,1.00,80408.0
comp8_rate_percent_diff,19127.0,15.91,18.61,2.00,7.00,11.00,19.00,1317.00,119263.0
click_bool,138390.0,1.00,0.00,1.00,1.00,1.00,1.00,1.00,0.0
gross_bookings_usd,138390.0,386.28,821.19,0.00,124.00,218.40,429.79,159292.38,0.0
booking_bool,138390.0,1.00,0.00,1.00,1.00,1.00,1.00,1.00,0.0