# Setting up

In [1]:
# IMPORTS
import pandas as pd
import time

In [2]:
# PARAMETERS

train_path = "data/basic_dataset.csv"
# for testing: train_path = "data/small_dataset.csv"
stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats.csv"
save_output = True

In [3]:
# LOAD DATA

start_time = time.time()
chunk = pd.read_csv(train_path, chunksize=1000000)
print(f"load chunk: {time.time() - start_time:.2f}s")

start_time = time.time()
df = pd.concat(chunk)
print(f"concat df: {time.time() - start_time:.2f}s")

load chunk: 0.03s
concat df: 15.60s

# Describing the dataset

### Describing the entire dataset

In [4]:
# save to csv the stats
stats = []

for column in df.columns:
    stats.append(df[column].describe())

df_stats = pd.concat(stats, axis=1).T

if save_output: df_stats.to_csv(stats_path)

In [5]:
df_stats.head()

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,4958347.0,2.479173e+06,1.431352e+06,0.00,1239586.50,2479173.00,3718759.50,4958346.0
srch_id,4958347.0,1.663666e+05,9.611223e+04,1.00,82936.00,166507.00,249724.00,332785.0
site_id,4958347.0,9.953133e+00,7.646890e+00,1.00,5.00,5.00,14.00,34.0
visitor_location_country_id,4958347.0,1.753405e+02,6.591625e+01,1.00,100.00,219.00,219.00,231.0
visitor_hist_starrating,251866.0,3.374334e+00,6.925186e-01,1.41,2.92,3.45,3.93,5.0

In [6]:
for row_name in df_stats.index:
     df_stats.loc[row_name, "count_missing"] = df[row_name].isna().sum()
     
if save_output: df_stats.to_csv(stats_path)

In [7]:
# describe the dataframe with describe method with 2 decimals
df.describe().round(2)

,Unnamed: 0,srch_id,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool,srch_query_affinity_score,random_bool,click_bool,gross_bookings_usd,booking_bool
count,4958347.00,4958347.00,4958347.00,4958347.00,251866.00,252988.00,4958347.00,4958347.00,4958347.00,4950983.00,...,4958347.00,4958347.00,4958347.00,4958347.00,4958347.0,317406.00,4958347.00,4958347.00,138390.00,4958347.00
mean,2479173.00,166366.56,9.95,175.34,3.37,176.02,173.97,70079.18,3.18,3.78,...,37.47,1.97,0.35,1.11,0.5,-24.15,0.30,0.04,386.28,0.03
std,1431351.63,96112.23,7.65,65.92,0.69,107.25,68.35,40609.92,1.05,1.05,...,51.99,0.86,0.73,0.42,0.5,15.74,0.46,0.21,821.19,0.16
min,0.00,1.00,1.00,1.00,1.41,0.00,1.00,1.00,0.00,0.00,...,0.00,1.00,0.00,1.00,0.0,-326.57,0.00,0.00,0.00,0.00
25%,1239586.50,82936.00,5.00,100.00,2.92,109.81,100.00,35010.00,3.00,3.50,...,4.00,2.00,0.00,1.00,0.0,-30.77,0.00,0.00,124.00,0.00
50%,2479173.00,166507.00,5.00,219.00,3.45,152.24,219.00,69638.00,3.00,4.00,...,17.00,2.00,0.00,1.00,1.0,-20.45,0.00,0.00,218.40,0.00
75%,3718759.50,249724.00,14.00,219.00,3.93,213.49,219.00,105168.00,4.00,4.50,...,48.00,2.00,0.00,1.00,1.0,-13.35,1.00,0.00,429.79,0.00
max,4958346.00,332785.00,34.00,231.00,5.00,1958.70,230.00,140821.00,5.00,5.00,...,492.00,9.00,9.00,8.00,1.0,-2.49,1.00,1.00,159292.38,1.00

### Describing only the booked rowss

In [8]:
temp_df = df[df.booking_bool == 1]
stats = []
for column in temp_df.columns:
    stats.append(temp_df[column].describe())
df_stats = pd.concat(stats, axis=1)

stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats_booked_rows.csv"
if save_output: df_stats.to_csv(stats_path)

In [9]:
for row_name in df_stats.index:
     df_stats.loc[row_name, "count_missing"] = temp_df[row_name].isna().sum()
     
if save_output: df_stats.to_csv(stats_path)

KeyError: 'count'