# Setting up

In [1]:
# IMPORTS
import pandas as pd
import time

In [2]:
# PARAMETERS

train_path = "data/basic_dataset.csv"
# for testing: train_path = "data/small_dataset.csv"
stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats.csv"
save_output = True

In [3]:
# LOAD DATA

start_time = time.time()
chunk = pd.read_csv(train_path, chunksize=1000000)
print(f"load chunk: {time.time() - start_time:.2f}s")

start_time = time.time()
df = pd.concat(chunk)
print(f"concat df: {time.time() - start_time:.2f}s")

load chunk: 0.02s
concat df: 41.71s

# Describing the dataset

### Describing the entire dataset

In [4]:
# save to csv the stats
stats = []

for column in df.columns:
    stats.append(df[column].describe())

df_stats = pd.concat(stats, axis=1).T

if save_output: df_stats.to_csv(stats_path)

In [5]:
df_stats.head()

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,4178070.0,2.089034e+06,1.206105e+06,0.00,1044517.25,2089034.50,3133551.75,4178069.0
srch_id,4178070.0,1.401913e+05,8.103217e+04,1.00,69732.00,140194.00,210350.00,280316.0
site_id,4178070.0,9.944782e+00,7.644517e+00,1.00,5.00,5.00,14.00,34.0
visitor_location_country_id,4178070.0,1.753963e+02,6.589292e+01,1.00,100.00,219.00,219.00,231.0
visitor_hist_starrating,211107.0,3.371564e+00,6.913020e-01,1.41,2.91,3.45,3.93,5.0

In [6]:
for row_name in df_stats.index:
     df_stats.loc[row_name, "count_missing"] = df[row_name].isna().sum()
     
if save_output: df_stats.to_csv(stats_path)

In [7]:
# describe the dataframe with describe method with 2 decimals
df.describe().round(2)

,Unnamed: 0,srch_id,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool,srch_query_affinity_score,random_bool,click_bool,gross_bookings_usd,booking_bool
count,4178070.00,4178070.00,4178070.00,4178070.00,211107.00,212039.00,4178070.00,4178070.00,4178070.00,4171855.00,...,4178070.0,4178070.00,4178070.00,4178070.00,4178070.0,265303.00,4178070.00,4178070.00,116430.00,4178070.00
mean,2089034.50,140191.33,9.94,175.40,3.37,176.33,174.11,70083.33,3.18,3.78,...,37.5,1.97,0.35,1.11,0.5,-24.11,0.30,0.04,384.32,0.03
std,1206105.06,81032.17,7.64,65.89,0.69,107.85,68.28,40613.12,1.05,1.05,...,52.1,0.86,0.73,0.42,0.5,15.84,0.46,0.21,720.64,0.16
min,0.00,1.00,1.00,1.00,1.41,9.35,1.00,1.00,0.00,0.00,...,0.0,1.00,0.00,1.00,0.0,-326.57,0.00,0.00,0.00,0.00
25%,1044517.25,69732.00,5.00,100.00,2.91,110.12,100.00,35022.00,3.00,3.50,...,4.0,2.00,0.00,1.00,0.0,-30.72,0.00,0.00,123.98,0.00
50%,2089034.50,140194.00,5.00,219.00,3.45,152.50,219.00,69636.00,3.00,4.00,...,17.0,2.00,0.00,1.00,1.0,-20.40,0.00,0.00,218.03,0.00
75%,3133551.75,210350.00,14.00,219.00,3.93,213.67,219.00,105179.00,4.00,4.50,...,48.0,2.00,0.00,1.00,1.0,-13.34,1.00,0.00,429.28,0.00
max,4178069.00,280316.00,34.00,231.00,5.00,1958.70,230.00,140821.00,5.00,5.00,...,492.0,9.00,9.00,8.00,1.0,-2.49,1.00,1.00,115309.14,1.00

### Describing only the booked rowss

In [12]:
temp_df = df[df.booking_bool == 1]
stats = []
for column in temp_df.columns:
    stats.append(temp_df[column].describe())
df_stats = pd.concat(stats, axis=1).T

stats_path = f"stats/{train_path.split('/')[1][:-4]}_stats_booked_rows.csv"
if save_output: df_stats.to_csv(stats_path)

In [13]:
df_stats

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,116430.0,2.090318e+06,1.205758e+06,12.0000,1.049632e+06,2.088222e+06,3.134360e+06,4.178051e+06
srch_id,116430.0,1.402775e+05,8.100852e+04,1.0000,7.008900e+04,1.401390e+05,2.104048e+05,2.803150e+05
site_id,116430.0,9.886601e+00,7.636980e+00,1.0000,5.000000e+00,5.000000e+00,1.400000e+01,3.400000e+01
visitor_location_country_id,116430.0,1.763198e+02,6.545245e+01,1.0000,1.000000e+02,2.190000e+02,2.190000e+02,2.310000e+02
visitor_hist_starrating,7619.0,3.365001e+00,6.949455e-01,1.4100,2.890000e+00,3.430000e+00,3.920000e+00,5.000000e+00
visitor_hist_adr_usd,7658.0,1.771902e+02,1.124541e+02,9.3500,1.101900e+02,1.521500e+02,2.129975e+02,1.958700e+03
prop_country_id,116430.0,1.746213e+02,6.780503e+01,1.0000,1.000000e+02,2.190000e+02,2.190000e+02,2.300000e+02
prop_id,116430.0,6.997030e+04,4.073093e+04,2.0000,3.465000e+04,6.925250e+04,1.048860e+05,1.408210e+05
prop_starrating,116430.0,3.312600e+00,9.510186e-01,0.0000,3.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00
prop_review_score,116333.0,3.940241e+00,7.973797e-01,0.0000,3.500000e+00,4.000000e+00,4.500000e+00,5.000000e+00
prop_brand_bool,116430.0,6.640814e-01,4.723126e-01,0.0000,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
prop_location_score1,116430.0,2.843460e+00,1.476811e+00,0.0000,1.790000e+00,2.710000e+00,3.950000e+00,6.950000e+00
prop_location_score2,104286.0,1.881997e-01,1.872273e-01,0.0000,5.000000e-02,1.271000e-01,2.639000e-01,1.000000e+00
prop_log_historical_price,116430.0,4.309345e+00,1.826259e+00,0.0000,4.480000e+00,4.930000e+00,5.290000e+00,6.210000e+00
position,116430.0,7.757897e+00,8.073811e+00,1.0000,2.000000e+00,4.000000e+00,1.000000e+01,4.000000e+01
price_usd,116430.0,2.752916e+02,1.761661e+04,0.0000,8.200000e+01,1.129450e+02,1.590000e+02,3.779565e+06
promotion_flag,116430.0,3.020785e-01,4.591611e-01,0.0000,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
srch_destination_id,116430.0,1.407827e+04,8.131182e+03,2.0000,7.104000e+03,1.374900e+04,2.116000e+04,2.841600e+04
srch_length_of_stay,116430.0,2.084626e+00,1.686353e+00,1.0000,1.000000e+00,2.000000e+00,3.000000e+00,2.800000e+01
srch_booking_window,116430.0,3.144595e+01,4.680620e+01,0.0000,3.000000e+00,1.300000e+01,3.900000e+01,4.800000e+02
srch_adults_count,116430.0,1.946053e+00,8.791873e-01,1.0000,1.000000e+00,2.000000e+00,2.000000e+00,9.000000e+00
srch_children_count,116430.0,3.667268e-01,7.369352e-01,0.0000,0.000000e+00,0.000000e+00,0.000000e+00,8.000000e+00
srch_room_count,116430.0,1.129863e+00,4.358993e-01,1.0000,1.000000e+00,1.000000e+00,1.000000e+00,8.000000e+00
srch_saturday_night_bool,116430.0,5.183973e-01,4.996636e-01,0.0000,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
srch_query_affinity_score,9074.0,-2.198206e+01,1.523361e+01,-323.9768,-2.747593e+01,-1.780880e+01,-1.227730e+01,-3.210200e+00
random_bool,116430.0,5.660053e-02,2.310787e-01,0.0000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
click_bool,116430.0,1.000000e+00,0.000000e+00,1.0000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
gross_bookings_usd,116430.0,3.843193e+02,7.206404e+02,0.0000,1.239825e+02,2.180300e+02,4.292750e+02,1.153091e+05
booking_bool,116430.0,1.000000e+00,0.000000e+00,1.0000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [14]:
for row_name in df_stats.index:
     df_stats.loc[row_name, "count_missing"] = temp_df[row_name].isna().sum()
     
if save_output: df_stats.to_csv(stats_path)